Revert "Refine Codex usages and Vue components"
This reverts commit a475796a766f085be75e9e7f7af65ab038df1253.

Reason for revert: startup.js:146 Error: Cannot require an undefined file codex.js; let's figure this out.

Change-Id: I71bcb7edcf06a36b47410482c5f3ea22f75b0fa2